services:
  - type: web
    name: dinanwuye-frontend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: "https://dinanwuye-back.onrender.com"
      - key: VITE_SUPABASE_URL
        value: "https://ysvqvrskwyyjbeepbyuc.supabase.co"
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
  - type: web
    name: dinanwuye-backend
    env: node
    plan: free
    buildCommand: pnpm install --frozen-lockfile --prod=false && pnpm --filter @dinanwuye/auth-service exec prisma generate --schema prisma/schema.prisma && pnpm --filter @dinanwuye/auth-service... run build
    startCommand: node auth-service/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: "1h"
      - key: SUPABASE_URL
        value: "https://ysvqvrskwyyjbeepbyuc.supabase.co"
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "https://dinanwuye.onrender.com"
    healthCheckPath: "/api/v1/health"
    healthCheckTimeout: 5